"""empty message

Revision ID: 0aa40dfc61c9
Revises: 50232c415b7b
Create Date: 2023-06-14 11:28:11.453170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa40dfc61c9'
down_revision = '50232c415b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('img_id', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('perfumes_perfumes_id_key', type_='unique')
        batch_op.drop_constraint('perfumes_perfumes_url_key', type_='unique')
        batch_op.create_unique_constraint(None, ['img_url'])
        batch_op.create_unique_constraint(None, ['img_id'])
        batch_op.drop_column('perfumes_url')
        batch_op.drop_column('perfumes_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfumes_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('perfumes_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('perfumes_perfumes_url_key', ['perfumes_url'])
        batch_op.create_unique_constraint('perfumes_perfumes_id_key', ['perfumes_id'])
        batch_op.drop_column('img_id')
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
