"""empty message

Revision ID: 0cc7e3009e40
Revises: 
Create Date: 2023-08-16 16:12:55.780084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc7e3009e40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=False),
    sa.Column('img_url', sa.String(length=100), nullable=False),
    sa.Column('accesorios_id', sa.String(length=120), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accesorios_id'),
    sa.UniqueConstraint('img_url')
    )
    op.create_table('perfumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=100), nullable=False),
    sa.Column('img_url', sa.String(length=100), nullable=False),
    sa.Column('img_id', sa.String(length=120), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_id'),
    sa.UniqueConstraint('img_url'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tshirts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('img_url', sa.String(length=100), nullable=False),
    sa.Column('tshirts_id', sa.String(length=120), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_url'),
    sa.UniqueConstraint('tshirts_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('role', sa.Enum('admin', 'buyer', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('tshirts_id', sa.Integer(), nullable=True),
    sa.Column('perfumes_id', sa.Integer(), nullable=True),
    sa.Column('accesorios_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accesorios_id'], ['accesorios.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['perfumes_id'], ['perfumes.id'], ),
    sa.ForeignKeyConstraint(['tshirts_id'], ['tshirts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartitem')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('tshirts')
    op.drop_table('perfumes')
    op.drop_table('accesorios')
    # ### end Alembic commands ###
