"""empty message

Revision ID: d5ce6bc1da0c
Revises: bfc26c8a4e7a
Create Date: 2023-06-08 10:40:19.997023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ce6bc1da0c'
down_revision = 'bfc26c8a4e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_cart_item_id_fkey', type_='foreignkey')
        batch_op.drop_column('cart_item_id')

    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cart', ['cart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cart_cart_item_id_fkey', 'cartitem', ['cart_item_id'], ['id'])

    # ### end Alembic commands ###
