"""empty message

Revision ID: f7171203eb5a
Revises: b8de7c0cd60b
Create Date: 2023-06-08 10:10:24.009105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7171203eb5a'
down_revision = 'b8de7c0cd60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cartitem', ['cart_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_item_id')

    # ### end Alembic commands ###
